
package agenceservice.hotel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelService", targetNamespace = "http://hotelservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNom", targetNamespace = "http://hotelservice/", className = "hotel.GetNom")
    @ResponseWrapper(localName = "getNomResponse", targetNamespace = "http://hotelservice/", className = "hotel.GetNomResponse")
    @Action(input = "http://hotelservice/IHotelService/getNomRequest", output = "http://hotelservice/IHotelService/getNomResponse")
    public String getNom();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVille", targetNamespace = "http://hotelservice/", className = "hotel.GetVille")
    @ResponseWrapper(localName = "getVilleResponse", targetNamespace = "http://hotelservice/", className = "hotel.GetVilleResponse")
    @Action(input = "http://hotelservice/IHotelService/getVilleRequest", output = "http://hotelservice/IHotelService/getVilleResponse")
    public String getVille();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtoiles", targetNamespace = "http://hotelservice/", className = "hotel.GetEtoiles")
    @ResponseWrapper(localName = "getEtoilesResponse", targetNamespace = "http://hotelservice/", className = "hotel.GetEtoilesResponse")
    @Action(input = "http://hotelservice/IHotelService/getEtoilesRequest", output = "http://hotelservice/IHotelService/getEtoilesResponse")
    public int getEtoiles();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<hotel.Chambre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookup", targetNamespace = "http://hotelservice/", className = "hotel.Lookup")
    @ResponseWrapper(localName = "lookupResponse", targetNamespace = "http://hotelservice/", className = "hotel.LookupResponse")
    @Action(input = "http://hotelservice/IHotelService/lookupRequest", output = "http://hotelservice/IHotelService/lookupResponse")
    public List<Chambre> lookup(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

}
