gcc -pthread bin/calculC.o src/noeudStack.c -o bin/noeud
gcc -pthread bin/calculC.o src/messageSender.c -o bin/sender

gcc -pthread bin/calculC.o exemple/racine.c -o exemple/racine
gcc -pthread bin/calculC.o exemple/noeud.c -o exemple/noeud


