gcc -pthread bin/calculC.o src/noeud.c -o bin/noeud
gcc -pthread bin/calculC.o src/messageSender.c -o bin/sender
gcc -pthread bin/calculC.o src/noeudStack.c -o bin/nStack


gcc -pthread bin/calculC.o exemple/test_Racine.c -o exemple/rac
gcc -pthread bin/calculC.o exemple/test_Noeud.c -o exemple/noeud